'use client';

import { useRef, useState } from 'react';
import CollapsibleCard from './CollapsibleCard';
import { ExpandIcon, PencilIcon, SparklesIcon } from '@/components/icons';
import { LYRICS_MAX } from '@/constants/create';

interface Props {
  lyrics: string;
  onLyricsChange: (v: string) => void;
  instrumental: boolean;
  disabled?: boolean;
}

type LyricsMode = 'auto' | 'write';

/**
 * Lyrics card matching Suno's design:
 *  - Header: [▾ Lyrics]  [Auto | Write]  [✨ AI]
 *  - Auto mode: greyed textarea with hint, generates lyrics on submit
 *  - Write mode: editable monospace textarea + char counter + expand
 */
export default function LyricsSection({
  lyrics,
  onLyricsChange,
  instrumental,
  disabled
}: Props) {
  const [mode, setMode] = useState<LyricsMode>('write');
  const taRef = useRef<HTMLTextAreaElement>(null);
  const isAuto = mode === 'auto';
  const remaining = LYRICS_MAX - lyrics.length;

  const lyricsLocked = disabled || instrumental;

  const headerAction = (
    <>
      {/* Auto / Write segmented toggle */}
      <div className="flex bg-neutral-800/60 rounded-full p-0.5 text-xs">
        {(['auto', 'write'] as const).map((m) => (
          <button
            key={m}
            type="button"
            onClick={() => setMode(m)}
            className={[
              'px-3 py-1 rounded-full transition-colors capitalize',
              mode === m
                ? 'bg-neutral-700 text-white'
                : 'text-neutral-400 hover:text-neutral-200'
            ].join(' ')}
          >
            {m}
          </button>
        ))}
      </div>
      <button
        type="button"
        title="Clear lyrics"
        onClick={() => onLyricsChange('')}
        disabled={lyricsLocked || !lyrics}
        className="p-1.5 rounded-lg text-neutral-400 hover:text-neutral-200 hover:bg-neutral-700 transition-colors disabled:opacity-30"
      >
        <SparklesIcon className="w-4 h-4" />
      </button>
    </>
  );

  return (
    <CollapsibleCard title="Lyrics" rightAction={headerAction}>
      {instrumental ? (
        <div className="text-sm text-neutral-500 italic py-6 text-center bg-neutral-950/40 rounded-xl border border-dashed border-neutral-800">
          Instrumental on — no lyrics needed
        </div>
      ) : isAuto ? (
        <div className="text-sm text-neutral-500 py-6 px-3 bg-neutral-950/40 rounded-xl border border-dashed border-neutral-800 leading-relaxed">
          Lyrics will be generated by AI based on <em>Styles</em> and <em>Title</em>.
          Click{' '}
          <button
            type="button"
            onClick={() => setMode('write')}
            className="underline underline-offset-2 text-neutral-300 hover:text-white"
          >
            Write
          </button>{' '}
          to write your own.
        </div>
      ) : (
        <div className="space-y-2">
          <div className="relative">
            <textarea
              ref={taRef}
              value={lyrics}
              onChange={(e) => onLyricsChange(e.target.value)}
              rows={7}
              maxLength={LYRICS_MAX}
              placeholder="Write some lyrics or leave blank for instrumental"
              disabled={lyricsLocked}
              className="scrollbar-thin w-full bg-neutral-900 border border-neutral-700 rounded-xl px-4 py-3 text-sm text-white placeholder-neutral-500 outline-none focus:border-neutral-500 resize-none disabled:opacity-50 transition-colors"
            />
            <span
              className={[
                'absolute bottom-3 right-3 text-[10px] tabular-nums pointer-events-none',
                remaining < 100 ? 'text-amber-400' : 'text-neutral-600'
              ].join(' ')}
            >
              {remaining}
            </span>
          </div>
        </div>
      )}
    </CollapsibleCard>
  );
}
